CREATE USER IF NOT EXISTS 'ze_user'@'%' IDENTIFIED BY 'localdev';

CREATE DATABASE IF NOT EXISTS `my_wiki` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
GRANT ALL PRIVILEGES ON my_wiki.* TO 'ze_user'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
